# Generated by Django 5.1.15 on 2026-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Usada para o Sérgio ser avisado dos aniversários.', null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=0, help_text='Sessões disponíveis. Cada reserva gasta 1 crédito.', verbose_name='Créditos (sessões)'),
        ),
    ]
