# Generated by Django 5.1.15 on 2026-07-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_phone_user_birth_date_user_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credits',
        ),
        migrations.AddField(
            model_name='user',
            name='sessoes_hybrid',
            field=models.PositiveIntegerField(default=0, help_text='Sessões de Hybrid disponíveis.', verbose_name='Sessões Hybrid'),
        ),
        migrations.AddField(
            model_name='user',
            name='sessoes_pt',
            field=models.PositiveIntegerField(default=0, help_text='Sessões de PT (individual) disponíveis.', verbose_name='Sessões PT'),
        ),
        migrations.AddField(
            model_name='user',
            name='sessoes_sg',
            field=models.PositiveIntegerField(default=0, help_text='Sessões de Small Group disponíveis.', verbose_name='Sessões Small Group'),
        ),
    ]
