# Generated by Django 5.1.15 on 2026-09-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_credits_user_sessoes_hybrid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consentimento_em',
            field=models.DateTimeField(blank=True, help_text='Quando o aluno aceitou a política, no registo. É a prova de consentimento que o RGPD exige — dizer que ele aceitou não chega, é preciso poder mostrar quando. Vazio nas contas criadas no painel (ex.: staff) e nas anteriores a isto existir.', null=True, verbose_name='Aceitou a política de privacidade em'),
        ),
    ]
