# Generated by Django 5.1.15 on 2026-09-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cache_do_travao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deve_mudar_password',
            field=models.BooleanField(default=False, help_text='Fica marcado quando o treinador gera uma password provisória. Enquanto estiver marcado, o aluno só consegue abrir a página de mudar a password — e desmarca-se sozinho quando ele a muda.', verbose_name='Tem de mudar a password?'),
        ),
    ]
