# Generated by Django 5.1.15 on 2026-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_deve_mudar_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consentimento_em',
            field=models.DateTimeField(blank=True, help_text='Quando aceitou a política de privacidade, no registo.', null=True, verbose_name='Aceitou a política de privacidade em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deve_mudar_password',
            field=models.BooleanField(default=False, help_text='O aluno tem de escolher uma password nova ao entrar.', verbose_name='Tem de mudar a password?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sessoes_hybrid',
            field=models.PositiveIntegerField(default=0, verbose_name='Sessões Hybrid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sessoes_pt',
            field=models.PositiveIntegerField(default=0, verbose_name='Sessões PT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sessoes_sg',
            field=models.PositiveIntegerField(default=0, verbose_name='Sessões Small Group'),
        ),
    ]
