# Generated by Django 5.1.15 on 2026-07-13 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=10, verbose_name='Tipo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Morada / indicações')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('number_of_sessions', models.PositiveIntegerField(verbose_name='Nº de sessões')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço (€)')),
                ('validity_days', models.PositiveIntegerField(default=90, help_text='Dias até o pack expirar, a contar da data de compra.', verbose_name='Validade (dias)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pack',
                'verbose_name_plural': 'Packs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('default_capacity', models.PositiveIntegerField(default=1, help_text='Nº de vagas sugerido para sessões deste tipo (ex.: 1 para PT, 3 para small group, 12 para aula de grupo).', verbose_name='Lotação por defeito')),
                ('is_online', models.BooleanField(default=False, help_text='Marca se for um serviço à distância (sem local físico).', verbose_name='É online?')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de serviço',
                'verbose_name_plural': 'Tipos de serviço',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_total', models.PositiveIntegerField(verbose_name='Sessões (total)')),
                ('sessions_used', models.PositiveIntegerField(default=0, verbose_name='Sessões usadas')),
                ('purchased_at', models.DateField(default=django.utils.timezone.now, verbose_name='Comprado em')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expira em')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='bookings.pack', verbose_name='Pack')),
            ],
            options={
                'verbose_name': 'Pack do aluno',
                'verbose_name_plural': 'Packs dos alunos',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddField(
            model_name='pack',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='Deixar vazio se o pack servir para qualquer serviço.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs', to='bookings.servicetype', verbose_name='Tipo de serviço'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Se vazio, usa-se o nome do tipo de serviço.', max_length=120, verbose_name='Título (opcional)')),
                ('start', models.DateTimeField(verbose_name='Início')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duração (minutos)')),
                ('capacity', models.PositiveIntegerField(help_text='Nº máximo de alunos nesta sessão.', verbose_name='Lotação (nº de vagas)')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('location', models.ForeignKey(blank=True, help_text='Deixar vazio se for uma sessão online.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='bookings.location', verbose_name='Local')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='bookings.servicetype', verbose_name='Tipo de serviço')),
                ('trainer', models.ForeignKey(blank=True, limit_choices_to={'is_trainer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Treinador')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Marcada'), ('cancelled', 'Cancelada'), ('attended', 'Compareceu'), ('no_show', 'Faltou')], default='booked', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('client_pack', models.ForeignKey(blank=True, help_text='Pack de onde saiu esta sessão (se aplicável).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.clientpack', verbose_name='Pack usado')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.session', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Marcação',
                'verbose_name_plural': 'Marcações',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'client'), name='unique_booking_por_sessao')],
            },
        ),
    ]
