# Generated by Django 5.1.15 on 2026-07-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='min_cancel_hours',
            field=models.PositiveIntegerField(default=0, help_text='Nº de horas antes do início até quando o aluno pode cancelar sozinho. 0 = sem restrição (ex.: aulas de grupo). Ex.: 12 para PT.', verbose_name='Antecedência mínima para cancelar (horas)'),
        ),
    ]
