# Generated by Django 5.1.15 on 2026-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_servicetype_min_cancel_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Pacote', 'verbose_name_plural': 'Pacotes'},
        ),
        migrations.RemoveField(
            model_name='pack',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='validity_days',
        ),
        migrations.AddField(
            model_name='pack',
            name='description',
            field=models.CharField(blank=True, help_text='Aparece no cartão do pacote no site.', max_length=200, verbose_name='Descrição curta'),
        ),
        migrations.AddField(
            model_name='pack',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='pack',
            name='whatsapp_message',
            field=models.TextField(blank=True, help_text='Mensagem já preenchida quando o aluno clica no pacote. Se vazio, é usada uma mensagem genérica.', verbose_name='Mensagem de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='number_of_sessions',
            field=models.PositiveIntegerField(verbose_name='Nº de sessões (créditos)'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preço (€)'),
        ),
    ]
