# Generated by Django 5.1.15 on 2026-07-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_pack_options_remove_pack_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='credit_type',
            field=models.CharField(choices=[('sg', 'Small Group'), ('pt', 'PT'), ('hybrid', 'Hybrid')], default='sg', help_text='Que tipo de sessões este pacote dá ao aluno.', max_length=10, verbose_name='Tipo de crédito'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='credit_type',
            field=models.CharField(choices=[('sg', 'Small Group'), ('pt', 'PT'), ('hybrid', 'Hybrid')], default='sg', help_text='Que tipo de sessões esta aula gasta. Ex.: uma aula de grupo é Small Group; um treino individual é PT.', max_length=10, verbose_name='Tipo de crédito'),
        ),
    ]
