# Generated by Django 5.1.15 on 2026-07-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_pack_credit_type_servicetype_credit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgramSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('start_time', models.TimeField(verbose_name='Hora de início')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Vazio usa a lotação por defeito do tipo de serviço.', null=True, verbose_name='Lotação')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duração (minutos)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('location', models.ForeignKey(blank=True, help_text='Vazio = sessão online.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_slots', to='bookings.location', verbose_name='Local (por defeito)')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_slots', to='bookings.servicetype', verbose_name='Tipo de serviço (por defeito)')),
            ],
            options={
                'verbose_name': 'Aula recorrente (programa semanal)',
                'verbose_name_plural': 'Programa semanal',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
