# Generated by Django 5.1.15 on 2026-07-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_weeklyprogramslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_pack',
        ),
        migrations.DeleteModel(
            name='ClientPack',
        ),
    ]
