# Generated by Django 5.1.15 on 2026-09-08 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_client_pack_delete_clientpack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(choices=[('sg', 'Small Group'), ('pt', 'PT'), ('hybrid', 'Hybrid')], max_length=10, verbose_name='Tipo de crédito')),
                ('quantidade', models.IntegerField(help_text='Positivo = créditos acrescentados; negativo = gastos.', verbose_name='Quantidade')),
                ('motivo', models.CharField(choices=[('compra', 'Créditos adicionados'), ('reserva', 'Reserva de aula'), ('cancelamento', 'O aluno cancelou'), ('aula_cancelada', 'A aula foi cancelada'), ('marcacao_apagada', 'Marcação apagada'), ('ajuste', 'Ajuste manual')], max_length=20, verbose_name='Motivo')),
                ('saldo_depois', models.PositiveIntegerField(help_text='O saldo desse tipo logo a seguir a este movimento.', verbose_name='Saldo depois')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('feito_por', models.ForeignKey(blank=True, help_text='Quem provocou o movimento. Vazio = automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Feito por')),
                ('session', models.ForeignKey(blank=True, help_text='A aula que originou o movimento, quando há uma.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='bookings.session', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Movimento de créditos',
                'verbose_name_plural': 'Movimentos de créditos',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='bookings_mo_client__ff70d9_idx')],
            },
        ),
    ]
