# Generated by Django 5.1.15 on 2026-09-16 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_movimentocredito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('a_espera', 'Na fila'), ('inscrito', 'Entrou na aula'), ('saiu', 'Saiu da fila')], default='a_espera', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entrou na fila em')),
                ('inscrito_em', models.DateTimeField(blank=True, help_text='Quando abriu vaga e esta pessoa passou a estar inscrita.', null=True, verbose_name='Entrou na aula em')),
                ('avisado_em', models.DateTimeField(blank=True, help_text='Quando o Sérgio confirmou que avisou o aluno.', null=True, verbose_name='Avisado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esperas', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='bookings.session', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Lista de espera',
                'verbose_name_plural': 'Listas de espera',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'client'), name='uma_entrada_por_aluno_e_aula')],
            },
        ),
    ]
