# Generated by Django 5.1.15 on 2026-09-16 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_listaespera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['session', 'status'], name='idx_marcacao_aula'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='idx_marcacao_aluno'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start'], name='idx_sessao_inicio'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_cancelled', 'start'], name='idx_sessao_ativa_inicio'),
        ),
    ]
